
import { RichDataMap } from './types';

export const RICH_DATA_MAP: RichDataMap = {
  "1": { title: "That Man Is Blest Who, Fearing God", meter: "CM", tune: "ST. AGNES", author: "Isaac Watts, 1707", composer: "John B. Dykes, 1866", lyrics: "" },
  "2": { title: "Wherefore Do the Nations Rage?", meter: "77 77 D", tune: "ABERYSTWYTH", author: "The Psalter, 1912", composer: "Joseph Parry, 1879", lyrics: "" },
  "3": { title: "O Lord, My Foes Are Multiplied", meter: "CM", tune: "MARTYRDOM", author: "The Book of Psalms for Worship", composer: "English Country Songs, 1893; Ralph Vaughan Williams, 1906", lyrics: "" },
  "4": { title: "Give Ear, God of My Righteousness", meter: "CM", tune: "BURFORD", author: "Trinity Psalter Hymnal", composer: "", lyrics: "" },
  "5": { title: "Listen to My Words, O LORD", meter: "77 77 D", tune: "ABERYSTWYTH", author: "Book of Psalms for Worship", composer: "Joseph Parry, 1879", lyrics: "" },
  "6": { title: "LORD, Do Not Chasten Me in Wrath", meter: "LM", tune: "OLIVE'S BROW", author: "Book of Psalms for Worship", composer: "William B. Bradbury, 1853", lyrics: "" },
  "7": { title: "O Lord My God, in You I Refuge Take", meter: "10 10 10 10", tune: "SONG 24", author: "Julie and Timothy Tennent", composer: "Orlando Gibbons, 1623", lyrics: "" },
  "9": { title: "O LORD, My Heart Will Praise You", meter: "76 76 D", tune: "LANCASHIRE", author: "Donald Owens, 2012", composer: "", lyrics: "" },
  "10": { title: "Why, LORD, Do You Stand Far Away", meter: "CM", tune: "DUNDEE", author: "Julie and Timothy Tennent", composer: "Scottish Psalter, 1615", lyrics: "" },
  "11": { title: "I in the LORD Do Put My Trust", meter: "CM", tune: "SALISBURY", author: "Scottish Psalter, 1650", composer: "Thomas Ravenscroft, 1621", lyrics: "" },
  "12": { title: "Help, Lord, for Men of Virtue Fail", meter: "CMD", tune: "SASHA", author: "Isaac Watts, 1719", composer: "Joah J. Pinkston, 1997", lyrics: "" },
  "13": { title: "How Long Will You Forget Me, Lord?", meter: "CM", tune: "ST. BOTOLPH", author: "Book of Psalms for Worship", composer: "", lyrics: "" },
  "14": { title: "Within His Heart the Fool Spoke", meter: "76 76 D", tune: "PASSION CHORALE", author: "Book of Psalms for Worship", composer: "Hans Leo Hassler, 1601; adapt. Johann Sebastian Bach, 1729", lyrics: "" },
  "15": { title: "Who, Lord, May Dwell Within Your Holy Place", meter: "10 10 10 10", tune: "MORECAMBE", author: "Julie and Timothy Tennent", composer: "Frederick C. Arkinson, 1870", lyrics: "" },
  "16": { title: "When in the Night I Meditate", meter: "CM", tune: "ST. PETER", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "17": { title: "Hear, O My LORD, Regard My Cry", meter: "86 86 88 88", tune: "DZOVE BOSW", author: "The Psalter, 1912", composer: "Armenian folk song", lyrics: "" },
  "18": { title: "Whom Should We Love Like Thee", meter: "66 66 88", tune: "LOVE UNKNOWN", author: "Henry Francis Lyte, 1834", composer: "John Ireland, 1918", lyrics: "" },
  "20": { title: "Jehovah Hear Thee in Thy Grief", meter: "LM", tune: "OLIVE'S BROW", author: "The Psalter, 1912", composer: "William B. Bradbury, 1853", lyrics: "" },
  "21": { title: "The King in Your Great Strength, O LORD", meter: "CMD", tune: "HIGH OVER ALL", author: "Book of Psalms for Worship", composer: "Scottish Air", lyrics: "" },
  "22": { title: "My God, My God, O Why", meter: "CMD", tune: "KINGSFOLD", author: "Book of Psalms for Singing", composer: "Ancient plainsong, 13th cent.; adapt. Thomas Helmore, 1854", lyrics: "" },
  "24": { title: "The Earth, With All That Dwell Therein", meter: "CM", tune: "ST. ANNE", author: "The Psalter, 1912", composer: "William Croft, 1708", lyrics: "" },
  "25": { title: "As unto You I Lift My Soul", meter: "CM", tune: "AZMON", author: "Julie and Timothy Tennent", composer: "Carl G. Gläser, 1828; arr. Lowell Mason, 1839", lyrics: "" },
  "26": { title: "LORD, Vindicate Me", meter: "CMD", tune: "OESTREICH", author: "Book of Psalms for Worship", composer: "Josh Bauder, 2017", lyrics: "" },
  "27": { title: "The LORD, My Savior, Is My Light", meter: "LM", tune: "BOURBON", author: "Anne, Steele", composer: "Hesperian Harp, 1848; harm. Louise McAllister, 1958", lyrics: "" },
  "28": { title: "To You I Call, O LORD My Rock", meter: "CM", tune: "ESSLINGEN", author: "Julie and Timothy Tennent", composer: "Adam Krieger, 1667", lyrics: "" },
  "29": { title: "Give to the LORD, Ye Sons of Fame", meter: "LM", tune: "DUKE STREET", author: "Isaac Watts, 1719", composer: "John Hatton, 1793", lyrics: "" },
  "30": { title: "Sing to the LORD, Ye Saints of His", meter: "LM", tune: "HERONGATE", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "31": { title: "In Thee, O Lord, I Put My Trust", meter: "CMD", tune: "OESTREICH", author: "Scottish Psalter, 1650", composer: "Josh Bauder, 2017", lyrics: "" },
  "32": { title: "How Blest Is He Whose Trespass", meter: "76 76 D", tune: "AURELIA", author: "The Psalter, 1912", composer: "Samuel S. Wesley, 1864", lyrics: "" },
  "33": { title: "Let All the Just to GOD, with Joy", meter: "CM", tune: "LAND OF REST", author: "Tate and Brady's New Version, 1696", composer: "", lyrics: "" },
  "34": { title: "All of My Days I'll Bless and Praise the Lord", meter: "10 10 10 10", tune: "MORECAMBE", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "36": { title: "My Heart Proclaims the One Who Sins", meter: "LM", tune: "CONTRITION", author: "st. 1–2, Michael E. Owens, 2016; st. 3–7, Isaac Watts, 1719", composer: "", lyrics: "" },
  "37": { title: "Fret Not Thyself", meter: "88 6 88 6", tune: "ARIEL", author: "The Psalter, 1912", composer: "Wolfgang Amadeus Mozart, 1756–1791; arr. Lowell Mason, 1836", lyrics: "" },
  "38": { title: "Amidst Thy Wrath, Remember Love", meter: "CM", tune: "CRIMOND", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "40": { title: "I Waited for the LORD", meter: "66 66 D", tune: "FINGAL", author: "The Book of Psalms for Singing", composer: "", lyrics: "" },
  "41": { title: "How Blest the Man", meter: "CMD", tune: "HIGH OVER ALL", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "43": { title: "O Vindicate and Plead My Cause", meter: "", tune: "ST. COLUMBA", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "44": { title: "O God, We Have Heard of Your Works", meter: "11 11 11 11", tune: "FOUNDATION", author: "Book of Psalms for Worship", composer: "", lyrics: "" },
  "45": { title: "My Heart Doth Overflow", meter: "SM", tune: "FESTAL SONG", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "47": { title: "All Peoples, Clap Your Hands for Joy", meter: "CMD", tune: "FOREST GREEN", author: "Book of Psalms for Singing", composer: "", lyrics: "" },
  "48": { title: "The LORD Is Great; with Worthy Praise", meter: "LMD", tune: "JERUSALEM", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "49": { title: "Hear This, All Ye People, Hear", meter: "77 77", tune: "CANTERBURY", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "51": { title: "God, Be Merciful to Me", meter: "77 77 77", tune: "REDHEAD", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "52": { title: "Why Boast in Evil, Mighty Man?", meter: "87 87 88 7", tune: "AUS TIEFER NOT", author: "Donald Owens, 2012", composer: "", lyrics: "" },
  "53": { title: "Lo, There Is No God in Heaven", meter: "87 87 87", tune: "PICARDY", author: "David P. Regier", composer: "", lyrics: "" },
  "54": { title: "O Save Me by Thy Name", meter: "SM", tune: "SOUTHWELL", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "55": { title: "Jehovah, to My Prayer Give Ear", meter: "CM", tune: "BURFORD", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "56": { title: "Be Gracious unto Me, O God", meter: "86 86 86", tune: "MORNING SONG", author: "Book of Psalms for Singing", composer: "", lyrics: "" },
  "57": { title: "Show Your Mercies, Lord, to Me", meter: "77 77 7", tune: "HENDON", author: "David P. Regier", composer: "", lyrics: "" },
  "58": { title: "Do You Speak Right Decrees, You Mute?", meter: "87 87 88 7", tune: "AUS TIEFER NOT", author: "Donald Owens, 2012", composer: "", lyrics: "" },
  "59": { title: "Deliver Me from Those, O God", meter: "CMD", tune: "SASHA", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "60": { title: "O God, Thou Hast Rejected Us", meter: "CM", tune: "CLINTON", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "61": { title: "O God, Regard My Humble Plea", meter: "88 6 88 6", tune: "INNSBRUCK", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "62": { title: "On God, on God My Soul Relies", meter: "LM", tune: "ROCKINGHAM", author: "Henry F. Lyte, 1793–1867", composer: "", lyrics: "" },
  "64": { title: "God, Hear My Voice", meter: "CM", tune: "BELMONT", author: "Book of Psalms for Worship", composer: "", lyrics: "" },
  "65": { title: "Praise Awaits You, God, in Zion", meter: "87 87 D", tune: "ABBOT'S LEIGH", author: "David P. Regier", composer: "", lyrics: "" },
  "71": { title: "In Thee, O LORD, I Put My Trust", meter: "CM", tune: "CRIMOND", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "72": { title: "Hail to the Lord's Anointed", meter: "76 76 D", tune: "ST. THEODULPH", author: "James Montgomery, 1822", composer: "", lyrics: "" },
  "73": { title: "O God, How Good Thou Art", meter: "66 56 66 5", tune: "OLIVET", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "74": { title: "Why Have You Long Rejected Us, O God?", meter: "10 10 10 10", tune: "EVENTIDE", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "75": { title: "To Thee, O God, We Render Thanks", meter: "CM", tune: "ARLINGTON", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "76": { title: "God Is Truly Known in Judah", meter: "87 87 87", tune: "REGENT SQUARE", author: "Book of Psalms for Worship", composer: "", lyrics: "" },
  "77": { title: "I Cried Aloud for God to Help", meter: "CMD", tune: "RESIGNATION", author: "Trinity Psalter Hymnal", composer: "", lyrics: "" },
  "78": { title: "Come Listen, O My People", meter: "CMD", tune: "KINGSFOLD", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "79": { title: "In Thy Heritage the Nations", meter: "87 87 D", tune: "BLAENWERN", author: "The Psalter, 1912, alt.", composer: "", lyrics: "" },
  "80": { title: "O Thou Great Shepherd of Thy Chosen Race", meter: "10 10 10 10 10 10", tune: "FINLANDIA", author: "James Langran, 1912", composer: "", lyrics: "" },
  "81": { title: "Sing to the Lord Aloud", meter: "SM", tune: "FESTAL SONG", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "82": { title: "Where'er His Creatures Gather", meter: "76 76 D", tune: "ANGEL'S STORY", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "83": { title: "O God, No Longer Hold Thy Peace", meter: "CMD", tune: "FOREST GREEN", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "84": { title: "How Lovely, LORD of Hosts, to Me", meter: "88 88 88", tune: "MELITA", author: "Book of Psalms for Worship", composer: "", lyrics: "" },
  "85": { title: "In Times of Old", meter: "10 10 10 with refrain", tune: "SINE NOMINE", author: "Dan Kreider and Dustin Battles", composer: "", lyrics: "" },
  "87": { title: "Zion, Founded on the Mountains", meter: "87 87 47", tune: "CORONAE", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "88": { title: "LORD, the God of My Salvation", meter: "87 87 D", tune: "EBENEZER", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "89": { title: "My Song Forever Shall Record", meter: "LMD", tune: "KEDRON", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "90": { title: "O God, Our Help in Ages Past", meter: "CM", tune: "ST. ANNE", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "91": { title: "Call Jehovah Thy Salvation", meter: "87 87 D", tune: "HYFRYDOL", author: "James Montgomery, 1822", composer: "", lyrics: "" },
  "92": { title: "It Is Good to Sing Your Praises", meter: "87 87 D", tune: "ELLESDIE", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "93": { title: "The LORD Reigns over All", meter: "SM", tune: "FESTAL SONG", author: "Trinity Psalter Hymnal", composer: "", lyrics: "" },
  "94": { title: "O LORD, Thou Judge of All the Earth", meter: "LM", tune: "DISTRESS", author: "Psalter 1912", composer: "", lyrics: "" },
  "95": { title: "Now with Joyful Exultation", meter: "87 87 D", tune: "BEECHER", author: "Psalter 1912", composer: "", lyrics: "" },
  "96": { title: "O Sing a New Song to the Lord", meter: "LM", tune: "TRURO", author: "The Psalter, 1912", composer: "Lowell Mason, 1830", lyrics: "" },
  "97": { title: "Jehovah Reigns, Let Earth Be Glad", meter: "LM", tune: "ELY", author: "The Psalter, 1912; alt.", composer: "Thomas Turton, 1844", lyrics: "" },
  "98": { title: "Sing a New Song to Jehovah", meter: "87 87 D", tune: "AUSTRIAN HYMN", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "99": { title: "God Is King Forever", meter: "11 12 12 10", tune: "NICAEA", author: "The Psalter, 1912", composer: "John B. Dykes, 1861", lyrics: "" },
  "100": { title: "All People That on Earth Do Dwell", meter: "LM", tune: "OLD HUNDREDTH", author: "Kethe, William; Ken, Thomas", composer: "Louis Bourgeois, Genevan Psalter, 1551", lyrics: "" },
  "101": { title: "Of Justice and of Grace I Sing", meter: "CM", tune: "NEW BRITAIN", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "102": { title: "Thou, O Lord, Art God Alone", meter: "77 77 D", tune: "ST. GEORGE'S WINDSOR", author: "The Psalter,1912", composer: "", lyrics: "" },
  "103": { title: "O My Soul, Bless Your Redeemer", meter: "87 87", tune: "STUTTGART", author: "Sabbath-School Psalmodist, 1866", composer: "", lyrics: "" },
  "104": { title: "Praise the LORD, My Soul! O Praise Him!", meter: "87 87 D", tune: "NETTLETON", author: "Sing Psalms, 2003", composer: "", lyrics: "" },
  "105": { title: "Give Thanks to the LORD God", meter: "11 11 11 11", tune: "ST. DENIO", author: "Sing Psalms, 2003", composer: "", lyrics: "" },
  "106": { title: "O Praise the LORD, for He Is Good", meter: "CMD", tune: "OESTREICH", author: "The Psalter, 1912, alt.", composer: "", lyrics: "" },
  "108": { title: "O LORD God My Heart Is Steadfast", meter: "87 87 D", tune: "PLEADING SAVIOR", author: "Sing Psalms 2003", composer: "", lyrics: "" },
  "109": { title: "God of My Mercy and My Praise", meter: "CM", tune: "ST. ETHELDREDA", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "110": { title: "The LORD Declares unto My Lord", meter: "CMD", tune: "ELLACOMBE", author: "David P. Regier", composer: "", lyrics: "" },
  "111": { title: "Praise the LORD with Exaltation", meter: "87 87", tune: "STUTTGART", author: "Charles H. Spurgeon, 1834–1892", composer: "", lyrics: "" },
  "112": { title: "Praise God! Blessed Is the Man", meter: "10 10 10 10", tune: "TOULON", author: "Sing Psalms 2003", composer: "", lyrics: "" },
  "113": { title: "Hallelujah! Raise, O Raise", meter: "77 77", tune: "MONKLAND", author: "Josiah Conder, 1854", composer: "", lyrics: "" },
  "114": { title: "When Israel out of Egypt Went", meter: "LM", tune: "DUKE STREET", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "115": { title: "Not to Our Names, Thou Only Just", meter: "10 10 10 10 10 10", tune: "FINLANDIA", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "116": { title: "I Love the LORD, Who Heard My Cry", meter: "CM", tune: "LAND OF REST", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "117": { title: "Praise Jehovah, All Ye Nations", meter: "87 87 D", tune: "AUSTRIAN HYMN", author: "The Psalter, 1912", composer: "Franz J. Haydn, 1797\n", lyrics: "" },
  "118": { title: "The Glorious Gates of Righteousness", meter: "86 86 86", tune: "CORONATION", author: "The Psalter, 1912", composer: "Oliver Holden, 1793", lyrics: "" },
  "120": { title: "In My Distress to God I Cried", meter: "CMD", tune: "KINGSFOLD", author: "Scottish Psalter, 1650", composer: "", lyrics: "" },
  "121": { title: "I to the Hills Will Lift Mine Eyes", meter: "CM", tune: "DUNDEE", author: "Scottish Psalter, 1650", composer: "", lyrics: "" },
  "122": { title: "Oh I Was Glad They Said to Me", meter: "LMD", tune: "JERUSALEM", author: "Ryan J. Martin, 2023", composer: "", lyrics: "" },
  "123": { title: "LORD, unto You I Lift My Eyes", meter: "LM", tune: "O WALY WALY", author: "David P. Regier, 2019", composer: "", lyrics: "" },
  "124": { title: "If the Lord Had Not Been with Us", meter: "87 87 D", tune: "BEACH SPRING", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "125": { title: "All Who, with Heart Confiding", meter: "76 76 D", tune: "AURELIA", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "126": { title: "When God Revealed His Gracious Name", meter: "CM", tune: "AZMON", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "127": { title: "Unless the LORD the House Shall Build", meter: "LM", tune: "HERONGATE", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "128": { title: "Blessed the Man That Fears Jehovah", meter: "87 87", tune: "RATHBURN", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "129": { title: "From My Youth Up, May Israel Say", meter: "CM", tune: "MARTYRDOM", author: "Nahum Tate & Nicholas Brady, 1696", composer: "", lyrics: "" },
  "130": { title: "Out of the Depths I Cry to Thee", meter: "87 87 88 7", tune: "AUS TIEFER NOT", author: "Martin Luther, 1524; tr. Catherine Winkwork, 1863, alt.", composer: "Martin Luther, 1524", lyrics: "" },
  "131": { title: "Not Haughty Is My Heart", meter: "SM", tune: "SOUTHWELL", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "132": { title: "Arise, O LORD, Our God, Arise", meter: "LM", tune: "HERR JESU CHRIST", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "133": { title: "How Beautiful the Sight", meter: "66 66 88", tune: "MILLENNIUM", author: "James Montgomery, 1854", composer: "", lyrics: "" },
  "134": { title: "You Faithful Servants of the LORD", meter: "LM", tune: "OLD HUNDREDTH", author: "David T. Koyzis, 2021", composer: "", lyrics: "" },
  "135": { title: "Praise the LORD! O Praise the LORD's Name", meter: "87 87 D", tune: "ODE TO JOY", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "137": { title: "By Rivers of Cruel Babylon", meter: "CM", tune: "MORNING SONG", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "138": { title: "With All My Heart My Thanks I'll Bring", meter: "LM", tune: "WESLEY", author: "Book of Psalms for Worship", composer: "", lyrics: "" },
  "139": { title: "LORD, Thou Hast Searched Me", meter: "LM", tune: "FEDERAL STREET", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "140": { title: "Deliver Me from Evil", meter: "76 76 D", tune: "PASSION CHORALE", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "141": { title: "O LORD, I Call upon You", meter: "CMD", tune: "LLANGLOFFAN", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "142": { title: "To God I Made My Sorrows Known", meter: "CMD", tune: "SASHA", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "143": { title: "Hear My Prayer, O Lord, and Listen", meter: "87 87 D", tune: "BEACH SPRING", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "144": { title: "Blessed Be the LORD, My Rock", meter: "66 66 88 with repeat", tune: "LENOX", author: "Book of Psalms for Worship", composer: "", lyrics: "" },
  "145": { title: "I Will Extol You, God My King", meter: "LMD", tune: "JERUSALEM", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "146": { title: "I'll Praise My Maker with My Breath", meter: "88 88 88", tune: "OLD 113TH", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "149": { title: "O Praise Ye the LORD", meter: "10 10 11 11", tune: "LYONS", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "150": { title: "Praise the Lord Who Reigns Above", meter: "76 76 77 76", tune: "AMSTERDAM", author: "Charles Wesley, 1743", composer: "", lyrics: "" },
  "151": { title: "Morning Prayer", meter: "LM", tune: "TALLIS CANON", author: "Ken, Thomas", composer: "Tallis, Thomas", lyrics: "" },
  "152": { title: "Evening Prayer", meter: "", tune: "", author: "Ken, Thomas", composer: "Tallis, Thomas", lyrics: "" },
  "153": { title: "Holy, Holy, Holy, Lord God Almighty", meter: "11 12 12 10", tune: "NICAEA", author: "Heber, Reginald", composer: "Dykes, John B.", lyrics: "" },
  "154": { title: "Round the Lord in Glory Seated", meter: "87 87 D", tune: "EBENEZER", author: "", composer: "", lyrics: "" },
  "155": { title: "The God of Abraham Praise", meter: "66 84 D", tune: "LEONI", author: "Maimonides, Moses; Judah, Daniel ben; Olivers, Thomas", composer: "Hebrew melody; Lyon, Meyer", lyrics: "" },
  "156": { title: "Praise God from Whom All Blessings Flow", meter: "LM", tune: "OLD HUNDREDTH", author: "Ken, Thomas", composer: "Bourgeois, Louis; Genevan Psalter", lyrics: "" },
  "157": { title: "Holy God, We Praise Your Name", meter: "78 78 77", tune: "GROSSER GOTT", author: "Te Deum; Franz, Ignace; Walworth, Clarence", composer: "Allgemeines Katholisches Gesangbuch; Schicht, Johann Gottfried", lyrics: "" },
  "158": { title: "Come, Thou Almighty King", meter: "664 6664", tune: "ITALIAN HYMN", author: "Anonymous", composer: "de Giardini, Felice", lyrics: "" },
  "159": { title: "All Creatures of Our God and King", meter: "LM with alleluias", tune: "LASST UNS ERFREUEN", author: "Francis of Assisi; Draper, William H.", composer: "Geistliche Kirchengesäng; arr. Williams, Ralph Vaughan", lyrics: "" },
  "160": { title: "Holy Trinity, Thanks and Praise to Thee", meter: "55 88 55", tune: "SEELENBRÄUTIGAM", author: "Nyberg, Lorenz T.", composer: "Drese, Adam", lyrics: "" },
  "161": { title: "Glory Be to the Father", meter: "", tune: "GREATOREX", author: "Gloria Patri", composer: "Greatorex, Henry W.", lyrics: "" },
  "162": { title: "Come, We That Love the Lord", meter: "SM", tune: "ST. THOMAS", author: "Watts, Isaac", composer: "Williams, Aaron", lyrics: "" },
  "163": { title: "My God, How Wonderful Thou Art", meter: "CM", tune: "ST. ETHELDREDA", author: "Faber, Frederick W.", composer: "Turton, Thomas", lyrics: "" },
  "164": { title: "Lo! God Is Here, Let Us Adore", meter: "88 88 88", tune: "VATER UNSER", author: "Tersteegen, Gerhard; Wesley, John", composer: "Attr. Luther, Martin; Geistliche Lieder, Leipzig", lyrics: "" },
  "165": { title: "Angel Voices, Ever Singing", meter: "85 85 87", tune: "ANGEL VOICES", author: "Pott, Francis", composer: "Monk, Edwin George", lyrics: "" },
  "166": { title: "Sing Praise to God Who Reigns Above", meter: "87 87 88 7", tune: "MIT FREUDEN ZART", author: "Schütz, Johann J.; Cox, Frances E.", composer: "Bohemian Brethren's Kirchengesäng", lyrics: "" },
  "167": { title: "God Himself Is with Us", meter: "6 68 6 68 6 66", tune: "ARNSBERG", author: "Tersteegen, Gerhard", composer: "Neander, Joachim", lyrics: "" },
  "168": { title: "Sing Hallelujah, Praise the Lord!", meter: "86 86 88 86", tune: "BECHLER", author: "Swertner, John", composer: "Bechler, John Christian", lyrics: "" },
  "169": { title: "Thee We Adore, Eternal Lord!", meter: "LM", tune: "MENDON", author: "Latin, 4th or 5th cent.; Cotterill, Thomas", composer: "Traditional German melody; arr. Dyer, Samuel", lyrics: "" },
  "170": { title: "Father, Most Holy", meter: "11 11 11 5", tune: "CHRISTE SANCTORUM", author: "Latin, O Pater Sancte; Dearmer, Pearcy", composer: "Paris Antiphoner, 1681", lyrics: "" },
  "171": { title: "O Worship the King", meter: "10 10 11 11", tune: "LYONS", author: "Grant, Robert", composer: "Haydn, J. Michael; Kraus, Joseph Martin", lyrics: "" },
  "172": { title: "Praise, My Soul, the King of Heaven", meter: "87 87 87", tune: "ANDREWS", author: "Lyte, Henry F.", composer: "Andrews, Mark", lyrics: "" },
  "173": { title: "Immortal, Invisible, God Only Wise", meter: "11 11 11 11", tune: "ST. DENIO", author: "Smith, Walter Chambers", composer: "Welsh hymn tune; John Roberts's Caniadau y Cyssegr, 1839", lyrics: "" },
  "174": { title: "Let All the World in Every Corner Sing", meter: "10 4 66 66 10 4", tune: "LUCKINGTON", author: "Herbert, George", composer: "Harwood, Basil", lyrics: "" },
  "175": { title: "How Marvelous God's Greatness!", meter: "76 76 D", tune: "BLOMSTERTID", author: "Briem, Valdimar; Pilcher, Charles Venn", composer: "Swedish Koralbok", lyrics: "" },
  "176": { title: "Stand Up and Bless the Lord", meter: "SM", tune: "ST. MICHAEL", author: "Montgomery, James", composer: "Genevan Psalter; Crotch, William", lyrics: "" },
  "177": { title: "O Lord of Heaven and Earth and Sea", meter: "888 4", tune: "ES IST KEIN TAG", author: "Wordsworth, Christopher", composer: "Geistliche Seelen-Freud", lyrics: "" },
  "178": { title: "Praise Ye the Father", meter: "11 11 11 6", tune: "FLEMMING", author: "Charles, Elizabeth Rundle", composer: "Flemming, Friedrich Ferdinand", lyrics: "" },
  "179": { title: "Give to Our God Immortal Praise", meter: "LM", tune: "WARRINGTON", author: "", composer: "", lyrics: "" },
  "180": { title: "Safely Through Another Week", meter: "77 77 77", tune: "DIX", author: "Newton, John", composer: "", lyrics: "" },
  "181": { title: "This Is My Father's World", meter: "SMD", tune: "TERRA BEATA", author: "Babcock, Maltbie D.", composer: "Traditional English melody; Sheppard, Franklin L.", lyrics: "" },
  "182": { title: "O Father, Thou Whose Love Profound", meter: "LM", tune: "ROCKINGHAM", author: "Cooper, Edward", composer: "", lyrics: "" },
  "183": { title: "O Spendor of God's Glory Bright", meter: "LM", tune: "PUER NOBIS", author: "Ambrose of Milan", composer: "Trier manuscript; Praetorius, Michael", lyrics: "" },
  "184": { title: "All Things Bright and Beautiful", meter: "76 76 with refrain", tune: "ALL THINGS BRIGHT", author: "Alexander, Cecil F.", composer: "Monk, William Henry", lyrics: "" },
  "185": { title: "Great Is Thy Faithfulness", meter: "11 10 11 10 with refrain", tune: "FAITHFULNESS", author: "Chisholm, Thomas O.", composer: "Runyan, William M.", lyrics: "" },
  "186": { title: "For the Beauty of the Earth", meter: "77 77 77", tune: "DIX", author: "Pierpoint, Folliott Sandford", composer: "Kocher, Conrad; Monk, William Henry; harm. The English Hymnal", lyrics: "" },
  "187": { title: "Let the Whole Creation Cry", meter: "77 77 D", tune: "SALZBURG", author: "Brooke, Stopford A.", composer: "Hintze, Jakob; Bach, Johann Sebastian; Hymns Ancient and Modern, 1861", lyrics: "" },
  "188": { title: "I Sing the Mighty Power of God", meter: "CMD", tune: "ELLACOMBE", author: "Brooke, Stopford A.", composer: "Wittenburg Gesangbuch, 1784; Monk, William Henry", lyrics: "" },
  "189": { title: "Give Praise to God", meter: "LM with refrain", tune: "SOLI DEO", author: "Boice, James Montgomery", composer: "Jones, Paul S.", lyrics: "" },
  "190": { title: "Now Thank We All Our God", meter: "67 67 66 66", tune: "NUN DANKET", author: "Rinkart, Martin; Winkworth, Catherine", composer: "Crüger, Johann; Mendelssohn, Felix", lyrics: "" },
  "191": { title: "Praise to the Lord, the Almighty", meter: "14 14 4 7 8", tune: "LOBE DEN HERREN", author: "Neander, Joachim; Winkworth, Catherine", composer: "Stralsund Gesangbuch, 1665", lyrics: "" },
  "192": { title: "Rejoice, Ye Pure in Heart", meter: "SM with refrain", tune: "MARION", author: "Plumptre, E. H.", composer: "Messiter, Arthur H.", lyrics: "" },
  "193": { title: "We Gather Together", meter: "12 11 12 11", tune: "KREMSER", author: "Anonymous Dutch hymn; Baker, Theodore", composer: "", lyrics: "" },
  "194": { title: "We Praise Thee, O God, Our Redeemer", meter: "12 11 12 11", tune: "KREMSER", author: "Cory, Julia Cady", composer: "Nederlandtsche Gedenckclanck, 1626; Kremser, Edward", lyrics: "" },
  "195": { title: "King of Glory, King of Peace", meter: "74 74 D", tune: "GWALCHMAI", author: "Herbert, George", composer: "Jones, Joseph David", lyrics: "" },
  "196": { title: "Lord, We Bow Before Your Glory", meter: "87 87 D", tune: "KIMARSONEVY", author: "Alexander, Eric J.", composer: "Jones, Paul S.", lyrics: "" },
  "197": { title: "When Morning Gilds the Skies", meter: "66 6 66 6", tune: "LAUDES DOMINI", author: "Sebastian Portner's Katholisches Gesangbuch, 1828; Caswall, Edward", composer: "Barnby, Joseph", lyrics: "" },
  "198": { title: "Fairest Lord Jesus", meter: "56 85 58", tune: "CRUSADER'S HYMN", author: "Munster Gesangbuch, 1677; Seiss, Joseph A.", composer: "Schlesische Volkslieder, 1842; Willis, Richard S.", lyrics: "" },
  "199": { title: "Jesus, Thy Boundless Love to Me", meter: "88 88 88", tune: "RYBURN", author: "Gerhardt, Paul; Wesley, John", composer: "Cocker, Norman", lyrics: "" },
  "200": { title: "How Sad Our State", meter: "CMD", tune: "SASHA", author: "Watts, Isaac", composer: "Pinkston, Joan J.", lyrics: "" },
  "201": { title: "A Debtor to Mercy Alone", meter: "LMD", tune: "TREWEN", author: "Toplady, Augustus M.", composer: "Evans, David Emlyn", lyrics: "" },
  "202": { title: "Lord, I Deserve Thy Deepest Wrath", meter: "LM", tune: "KEDRON", author: "Manly, Basil; The Baptist Psalmody, 1850", composer: "Dare, Elkanah Kelsay", lyrics: "" },
  "203": { title: "Come, Ye Sinners, Poor and Needy", meter: "87 87", tune: "RESTORATION", author: "Hart, Joseph", composer: "Southern Harmony, 1835", lyrics: "" },
  "204": { title: "Lord Jesus, Think on Me", meter: "SM", tune: "SOUTHWELL", author: "Synesius of Cyrene; Chatfield, Allen W.", composer: "", lyrics: "" },
  "205": { title: "Depth of Mercy! Can There Be", meter: "77 77", tune: "CANTERBURY", author: "Wesley, Charles", composer: "Gibbons, Orlando", lyrics: "" },
  "206": { title: "Come to the Waters", meter: "11 10 11 10", tune: "WATER OF LIFE", author: "Boice, James Montgomery", composer: "Jones, Paul S.", lyrics: "" },
  "207": { title: "Ho! Ye That Thirst", meter: "CMD", tune: "FOREST GREEN", author: "Scottish Psalter, 1880", composer: "Trad. English melody; Vaughan Williams, Ralph", lyrics: "" },
  "208": { title: "No, Not Despairingly", meter: "64 64 66 4", tune: "NENTHORN", author: "Bonar, Horatius", composer: "Hately, Thomas Legerwood", lyrics: "" },
  "209": { title: "I Lay My Sins on Jesus", meter: "76 76 D", tune: "AURELIA", author: "Bonar, Horatius", composer: "", lyrics: "" },
  "210": { title: "Rock of Ages", meter: "77 77 77", tune: "REDHEAD", author: "Toplady, Augustus M.", composer: "Redhead, Richard", lyrics: "" },
  "211": { title: "O Come, O Come, Emmanuel", meter: "88 88 88", tune: "VENI EMMANUEL", author: "Latin hymn; Neale, John Mason", composer: "Ancient plaingsong; Helmore, Thomas", lyrics: "" },
  "212": { title: "Comfort, Comfort, Ye My People", meter: "87 87 88", tune: "GENEVAN 42", author: "Olearius, Johann; Winkworth, Catherine", composer: "Genevan Psalter, 1551", lyrics: "" },
  "213": { title: "On Jordan's Banks the Baptist's Cry", meter: "LM", tune: "PUER NOBIS", author: "Coffin, Charles; Chandler, John", composer: "", lyrics: "" },
  "214": { title: "Lo! He Comes with Clouds Descending", meter: "87 87 12 7", tune: "HELMSLEY", author: "Wesley, Charles", composer: "Olivers, Thomas; Vaughan Williams, Ralph", lyrics: "" },
  "215": { title: "Hark! the Glad Sound! The Savior Comes", meter: "CM", tune: "GRÄFENBERG", author: "Doddridge, Philip", composer: "Crüger, Johann", lyrics: "" },
  "216": { title: "Christ Is Coming! Let Creation", meter: "87 87 87 with repeat", tune: "CWM RHONDDA", author: "MacDuff, John R.", composer: "", lyrics: "" },
  "217": { title: "O Lord, How Shall I Meet You?", meter: "76 76 D", tune: "WIE SOLL ICH DICH EMPFANGEN", author: "Gerhardt, Paul; Winkworth, Catherine", composer: "Crüger, Johann", lyrics: "" },
  "218": { title: "Wake, Awake, for Night Is Flying", meter: "", tune: "WACHET AUF", author: "Nicolai, Philipp; Winkworth, Catherine", composer: "Sachs, Hans; Nicolai, Philipp; Bach, Johann Sebastian", lyrics: "" },
  "219": { title: "Joy to the World", meter: "CM with repeats", tune: "ANTIOCH", author: "Watts, Isaac", composer: "Handel, G. F.; Mason, Lowell", lyrics: "" },
  "220": { title: "Jesus Shall Reign", meter: "LM", tune: "DUKE STREET", author: "Watts, Isaac", composer: "Hatton, John", lyrics: "" },
  "221": { title: "The King Shall Come", meter: "CM", tune: "MORNING SONG", author: "Ancient Greek hymn; Brownlie, John", composer: "Traditional American melody; Kentucky Harmony, 1813, Part Second", lyrics: "" },
  "222": { title: "My Soul Now Magnifies the Lord (Magnificat)", meter: "LM", tune: "DEO GRACIAS", author: "Hermann Bonnus, 1548; tr. John T. Mueller, 1967", composer: "", lyrics: "" },
  "223": { title: "Blessed Be God, the Lord of Israel (Benedictus)", meter: "87 87 D", tune: "BEACH SPRING", author: "Trinity Psalter Hymnal", composer: "", lyrics: "" },
  "224": { title: "Angels We Have Heard on High", meter: "77 77 with refrain", tune: "GLORIA", author: "Trad. French carol; Crown of Jesus, 1862", composer: "Trad. French melody; Barnes, Edward S.", lyrics: "" },
  "225": { title: "Now Let Your Servant, Lord (Nunc Dimittis)", meter: "67 76 67", tune: "NUNC DIMITTIS", author: "William Helder, 2009", composer: "", lyrics: "" },
  "226": { title: "Come, Thou Long-Expected Jesus", meter: "87 87 D", tune: "HYFRYDOL", author: "Wesley, Charles", composer: "Prichard, Rowland H.; Vaughan Williams, Ralph", lyrics: "" },
  "227": { title: "Hark! the Herald Angels Sing", meter: "77 77 D with refrain", tune: "MENDELSSOHN", author: "Wesley, Charles; Whitefield, George", composer: "Mendelssohn, Felix; Cummings, William H.", lyrics: "" },
  "228": { title: "Savior of the Nations, Come", meter: "77 77", tune: "NUM KOMM, DER HEIDEN HEILAND", author: "Ambrose of Milan; Luther, Martin; Reynolds, William M.", composer: "Enchiridia, Erfurt, 1524; Calvisius, Seth", lyrics: "" },
  "229": { title: "Let All Mortal Flesh Keep Silence", meter: "87 87 87", tune: "PICARDY", author: "Liturgy of St. James; Moultrie, Gerard", composer: "French melody; Vaughan Williams, Ralph", lyrics: "" },
  "230": { title: "Away in a Manger", meter: "11 11 11 11", tune: "CRADLE SONG", author: "Anonymous", composer: "Kirkpatrick, William J.", lyrics: "" },
  "231": { title: "What Child Is This?", meter: "87 87 68 67", tune: "GREENSLEEVES", author: "Dix, William C.", composer: "Traditional English melody; Stainer, John", lyrics: "" },
  "232": { title: "O Little Town of Bethlehem", meter: "CMD", tune: "FOREST GREEN", author: "Brooks, Phillips", composer: "English folk tune; Vaughan Williams, Ralph", lyrics: "" },
  "233": { title: "How Bright Appears the Morning Star", meter: "88 78 87 48 48", tune: "WIE SCHÖN LEUCHTET", author: "Nicolai, Philipp; Mercer, William", composer: "Nicolai, Philipp; Bach, Johann Sebastian", lyrics: "" },
  "234": { title: "Love Came down at Christmas", meter: "67 67", tune: "CULBACH", author: "Rossetti, Christina", composer: "Scheffler's Heilige Seelenlust, 1657", lyrics: "" },
  "235": { title: "Gentle Mary Laid Her Child", meter: "76 76 D", tune: "TEMPUS ADEST FLORIDUM", author: "Cook, Joseph S.", composer: "Piae Cantiones, 1582; Macmillan, Ernest", lyrics: "" },
  "236": { title: "Once in Royal David's City", meter: "87 87 77", tune: "IRBY", author: "Alexander, Cecil Francis", composer: "Gauntlett, Henry", lyrics: "" },
  "237": { title: "Christians, Awake!", meter: "10 10 10 10 10 10", tune: "YORKSHIRE", author: "Byrom, John", composer: "Wainwright, John", lyrics: "" },
  "238": { title: "Good Christian Men, Rejoice", meter: "66 77 78 55", tune: "IN DULCI JUBILO", author: "Latin carol, 14th cent.", composer: "German carol, 14th cent.", lyrics: "" },
  "239": { title: "Silent Night", meter: "", tune: "STILLE NACHT", author: "Mohr, Joseph; Young, John F.; Anonymous", composer: "Gruber, Franz", lyrics: "" },
  "240": { title: "Break Forth, O Beauteous Heavenly Light", meter: "87 87 88 77", tune: "ERMUNTRE DICH", author: "Rist, Johann; Troutbeck, John; Russell, A. T.", composer: "Schop, Johann; Bach, Johann Sebastian", lyrics: "" },
  "241": { title: "On Christmas Night All Christians Sing", meter: "88 88 88", tune: "SUSSEX CAROL", author: "Traditional English carol", composer: "Traditional carol melody; Vaughan Williams, Ralph", lyrics: "" },
  "242": { title: "The First Noel", meter: "", tune: "THE FIRST NOWELL", author: "Traditional English carol", composer: "W. Sandy's Christmas Carols, 1833", lyrics: "" },
  "243": { title: "Infant Holy, Infant Lowly", meter: "87 87 88 77", tune: "W ZLOBIE LEZY", author: "Polish carol; Reed, Edith M. G.", composer: "Polish folk melody", lyrics: "" },
  "244": { title: "Lo, How a Rose E'er Blooming", meter: "76 76 676", tune: "ES IST EIN' ROS'", author: "German carol; Baker, Theodore; Spaeth, Harriet; Mattes, John", composer: "German melody; Praetorius, Michael", lyrics: "" },
  "245": { title: "From Heaven Above to Earth I Come", meter: "LM", tune: "VOM HIMMEL HOCH", author: "Luther, Martin; Winkworth, Catherine", composer: "Luther, Martin; Valentin Schumann's Geistliche Lieder, 1539", lyrics: "" },
  "246": { title: "In the Bleak Midwinter", meter: "", tune: "CRANHAM", author: "Rossetti, Christina", composer: "Holst, Gustav", lyrics: "" },
  "247": { title: "All My Heart This Night Rejoices", meter: "8336 8336", tune: "WARUM SOLLT' ICH MICH DENN GRÄMEN", author: "Gerhardt, Paul; Winkworth, Catherine", composer: "Ebeling, Johann G.", lyrics: "" },
  "248": { title: "See amid the Winter's Snow", meter: "77 77 with refrain", tune: "HUMILITY", author: "Caswall, Edward", composer: "Goss, John", lyrics: "" },
  "249": { title: "Angels from the Realms of Glory", meter: "87 87 87", tune: "REGENT SQUARE", author: "Montgomery, James", composer: "Smart, Henry T.", lyrics: "" },
  "250": { title: "God Rest You Merry, Gentlemen", meter: "", tune: "GOD REST YOU MERRY", author: "Traditional English carol, 18th cent.", composer: "Traditional English melody", lyrics: "" },
  "251": { title: "Behold, the Great Creator", meter: "CM", tune: "THIS ENDRIS NYGHT", author: "Pestel, Thomas; Sermons and Devotions Old and New, 1639", composer: "English carol, 15th cent.", lyrics: "" },
  "252": { title: "Of the Father's Love Begotten", meter: "87 87 87 7", tune: "DIVINUM MYSTERIUM", author: "Prudentius, Marcus Aurelius C.; Neale, John Mason", composer: "Plainsong", lyrics: "" },
  "253": { title: "O Come, All Ye Faithful", meter: "", tune: "ADESTE FIDELES", author: "Wade, John Francis; Oakeley, Frederick", composer: "Wade, John F.; Cantus Diversi, 1751; The English Hymnal, 1906", lyrics: "" },
  "254": { title: "While Shepherds Watched Their Flocks", meter: "CM", tune: "WINCHESTER OLD", author: "Tate, Nahum", composer: "Este's Psalmes, 1592", lyrics: "" },
  "255": { title: "As with Gladness, Men of Old", meter: "77 77 77", tune: "DIX", author: "Dix, William Chatterton", composer: "", lyrics: "" },
  "256": { title: "Hosanna, Loud Hosanna", meter: "76 76 D", tune: "ELLACOMBE", author: "Threlfall, Jennette", composer: "", lyrics: "" },
  "257": { title: "All Glory, Laud, and Honor", meter: "76 76 D", tune: "ST. THEODULPH", author: "Theodulph of Orleans; Neale, John Mason", composer: "Teschner, Melchior", lyrics: "" },
  "258": { title: "O Love, How Deep", meter: "LM", tune: "DEO GRACIAS", author: "á Kempis, Thomas; Webb, Benjamin", composer: "English melody; Hymns Ancient and Modern, Revised, 1950", lyrics: "" },
  "259": { title: "Ride on, Ride on in Majesty!", meter: "LM", tune: "TRURO", author: "Milman, Henry Hart", composer: "Thomas Williams's Psalmodia Evangelica, 1789", lyrics: "" },
  "260": { title: "My Song Is Love Unknown", meter: "66 66 44 44", tune: "LOVE UNKNOWN", author: "Crossman, Samuel", composer: "Ireland, John", lyrics: "" },
  "261": { title: "O Sacred Head, Now Wounded", meter: "76 76 D", tune: "PASSION CHORALE", author: "Bernard of Clairvaux; Gerhart, Paul; Alexander, James W.", composer: "Hassler, Hans Leo; Bach, Johann Sebastian", lyrics: "" },
  "262": { title: "Alas and Did My Savior Bleed", meter: "CM", tune: "MARTYRDOM", author: "Watts, Isaac", composer: "Hugh Wilson", lyrics: "" },
  "263": { title: "Man of Sorrows, What a Name", meter: "777 8", tune: "MAN OF SORROWS", author: "Bliss, Philip P.", composer: "Bliss, Philip P.", lyrics: "" },
  "264": { title: "Go to Dark Gethsemane", meter: "77 77 77", tune: "REDHEAD", author: "Montgomery, James", composer: "", lyrics: "" },
  "265": { title: "Throned upon the Awful Tree", meter: "77 77 77", tune: "ARFON", author: "Ellerton, John", composer: "Traditional Welsh melody; Davies, Hugh", lyrics: "" },
  "266": { title: "Stricken, Smitten, and Afflicted", meter: "87 87 D", tune: "O MEIN JESU, ICH MUSS STERBEN", author: "Kelly, Thomas", composer: "Geistliche Volkslieder, Paderborn, 1850", lyrics: "" },
  "267": { title: "In the Cross of Christ I Glory", meter: "87 87", tune: "RATHBURN", author: "Bowring, John", composer: "Conkey, Ithamar", lyrics: "" },
  "268": { title: "His Be the Victor's Name", meter: "SM", tune: "FESTAL SONG", author: "Gandy, Samuel Whitelock", composer: "Walter, Wiliam Henry", lyrics: "" },
  "269": { title: "The Perfect Righteousness of God", meter: "LM", tune: "MENDON", author: "Midlane, Albert", composer: "Traditional German melody; Dyer, Samuel", lyrics: "" },
  "270": { title: "What Wondrous Love Is This?", meter: "12 9 12 12 9", tune: "WONDROUS LOVE", author: "American folk hymn; Stith Mead's General Selection, 1811", composer: "William Walker's Southern Harmony, 2nd ed., 1840", lyrics: "" },
  "271": { title: "Tis Finished! The Messiah Dies", meter: "LM", tune: "OLIVE'S BROW", author: "Wesley, Charles", composer: "Bradbury, William B.", lyrics: "" },
  "272": { title: "Ah, Holy Jesus", meter: "11 11 11 5", tune: "HERZLIEBSTER JESU", author: "Heerman, Johann; Bridges, Robert", composer: "Crüger, Johann", lyrics: "" },
  "273": { title: "When I Survey the Wondrous Cross", meter: "LM", tune: "HAMBURG", author: "Watts, Isaac", composer: "Mason, Lowell", lyrics: "" },
  "274": { title: "Tis Midnight; and on Olive's Brow", meter: "LM", tune: "OLIVE'S BROW", author: "Tappan, William B.", composer: "", lyrics: "" },
  "275": { title: "He Dies! The Friend of Sinners Dies!", meter: "LM", tune: "BLOCKLEY", author: "Watts, Isaac; Toplady, Augustus M.", composer: "Blockley, Thomas", lyrics: "" },
  "276": { title: "Priest and Victim, Jesus Dies", meter: "77 77 77", tune: "RABUN", author: "Clarkson, Margaret", composer: "Pinner, Brian", lyrics: "" },
  "277": { title: "It Is a Thing Most Wonderful", meter: "LM", tune: "HERONGATE", author: "How, William Walsham", composer: "Traditional English melody; Vaughan Williams, Ralph", lyrics: "" },
  "278": { title: "Christ, the Life of All the Living", meter: "87 87 88 77", tune: "JESU, MEINES LEBENS LEBEN", author: "Homburg, Ernst; Winkworth, Catherine", composer: "Das grosse Cantionale, Darnstadt", lyrics: "" },
  "279": { title: "Sing, My Tongue, the Glorious Battle", meter: "87 87 87", tune: "RHUDDLAN", author: "Fortunatus, Venantius Honorius Clementianus; Neale, John Mason", composer: "Traditional Welsh melody; The English Hymnal, 1906", lyrics: "" },
  "280": { title: "Hark! the Voice of Love and Mercy", meter: "87 87 444 77", tune: "BRYN CALFARIA", author: "Evans, Jonathan", composer: "Owen, William", lyrics: "" },
  "281": { title: "Christ, the Lord, Is Risen Today", meter: "77 77 with alleluias", tune: "EASTER HYMN", author: "Wesley, Charles", composer: "Lyra Davidica, 1708", lyrics: "" },
  "282": { title: "Jesus Christ Is Risen Today", meter: "77 77 with alleluias", tune: "LLANFAIR", author: "Latin hymn; Lyra Davidica, 1708", composer: "Williams, Robert", lyrics: "" },
  "283": { title: "Thine Be the Glory", meter: "10 11 11 11 with refrain", tune: "JUDAS MACCABEUS", author: "Budry, Edmond Louis; Hoyle, R. Birch", composer: "Handel, George Frederic", lyrics: "" },
  "284": { title: "Alleluia, Alleluia! Hearts to Heaven", meter: "87 87 D", tune: "ODE TO JOY", author: "Wordsworth, Christopher", composer: "van Beethoven, Ludwig; Hodges, Edward", lyrics: "" },
  "285": { title: "The Day of Resurrection", meter: "76 76 D", tune: "LANCASHIRE", author: "John of Damascus; Neale, John Mason", composer: "Smart, Henry", lyrics: "" },
  "286": { title: "Jesus Lives, and So Shall I", meter: "78 78 77", tune: "ZUVERSICHT", author: "Gellert, Christian F.; Lang, John Dunmore", composer: "Crüger, Johann", lyrics: "" },
  "287": { title: "Good Christians, All Rejoice and Sing", meter: "888 with alleluias", tune: "GELOBT SEI GOTT", author: "Alington, Cyril A.", composer: "Vulpius, Melchior", lyrics: "" },
  "288": { title: "The Strife Is Over", meter: "888 4 with alleluias", tune: "VICTORY", author: "Latin hymn; Pott, Francis", composer: "de Palestrina, Giovanni P.; Monk, William Henry", lyrics: "" },
  "289": { title: "I Know That My Redeemer Lives", meter: "LM", tune: "DUKE STREET", author: "Medley, Samuel", composer: "", lyrics: "" },
  "290": { title: "This Joyful Eastertide", meter: "67 67 with refrain", tune: "VRUECHTEN", author: "Woodward, George Ratcliff", composer: "Davids Psalmen, Amsterdam, 1684", lyrics: "" },
  "291": { title: "Rejoice, the Lord is King", meter: "66 66 88", tune: "DARWALL", author: "Wesley, Charles", composer: "Darwall, John", lyrics: "" },
  "292": { title: "Christ Jesus Lay in Death's Strong Bands", meter: "87 87 78 74", tune: "CHRIST LAG IN TODESBANDEN", author: "Luther, Martin; Latin Victimae Paschall; Massie, Richard", composer: "Latin melody, 1100; Walther, Johann", lyrics: "" },
  "293": { title: "Look, Ye Saints, the Sight Is Glorious", meter: "87 87 47", tune: "CORONAE", author: "Kelly, Thomas", composer: "Monk, William Henry", lyrics: "" },
  "294": { title: "Lamb of God, Thou Now Art Seated", meter: "87 87 D", tune: "ABBOT'S LEIGH", author: "Deck, James George", composer: "Zundel, John", lyrics: "" },
  "295": { title: "The Head That Once Was Crowned with Thorns", meter: "CM", tune: "ST. MAGNUS", author: "Kelly, Thomas", composer: "Clarke, Jeremiah", lyrics: "" },
  "296": { title: "Alleluia! Sing to Jesus", meter: "87 87 D", tune: "HYFRYDOL", author: "Dix, William C.", composer: "Prichard, Rowland H.", lyrics: "" },
  "297": { title: "Hail, Thou Once-Despised Jesus!", meter: "87 87 D", tune: "RUSTINGTON", author: "Bakewell, John; Toplady, Augustus M.", composer: "Parry, C. Hubert H.", lyrics: "" },
  "298": { title: "Behold the Glories of the Lamb", meter: "CM", tune: "LYNGHAM", author: "", composer: "", lyrics: "" },
  "299": { title: "Jesus, in His Heavenly Glory", meter: "87 87", tune: "STUTTGART", author: "Chapman, Robert C.", composer: "Witt's Psalmodia Sacra, Gotha, 1715", lyrics: "" },
  "300": { title: "Our Great High Priest Is Sitting", meter: "76 76 D", tune: "MEIRIONYDD", author: "Cecil, A. P.", composer: "Lloyd, William", lyrics: "" },
  "301": { title: "All Hail the Power of Jesus' Name (Coronation)", meter: "CM", tune: "CORONATION", author: "Perronet, Edward; Rippon, John", composer: "Holden, Oliver", lyrics: "" },
  "302": { title: "All Hail the Power of Jesus' Name (Diadem)", meter: "86 68 with refrain", tune: "DIADEM", author: "Edward Perronet, 1779; alt. John Rippon, 1787", composer: "James Ellor, 1838", lyrics: "" },
  "303": { title: "Lord, Enthroned in Heavenly Splendor", meter: "87 87 87", tune: "LAUDA ANIMA", author: "Bourne, George H.", composer: "Goss, John", lyrics: "" },
  "304": { title: "Jesus, the Name High over All", meter: "CMD", tune: "HIGH OVER ALL", author: "Wesley, Charles", composer: "Scottish Air", lyrics: "" },
  "305": { title: "Majestic Sweetness Sits Enthroned", meter: "CM with repeat", tune: "ORTONVILLE", author: "Stennett, Samuel", composer: "Hastings, Thomas", lyrics: "" },
  "306": { title: "Crown Him with Many Crowns", meter: "SMD", tune: "DIADEMATA", author: "Bridges, Matthew; Thring, Godfrey", composer: "Elvey, George J.", lyrics: "" },
  "307": { title: "Come, Christians, Join to Sing", meter: "66 66 D", tune: "MADRID", author: "Bateman, Christian H.", composer: "Traditional Spanish melody; Evans, David Emlyn", lyrics: "" },
  "308": { title: "Come Down, O Love Divine", meter: "66 65 D", tune: "DOWN AMPNEY", author: "da Siena, Bianco; Littledale, Richard Frederick", composer: "Vaughan Williams, Ralph", lyrics: "" },
  "309": { title: "Spirit of God, Descend upon My Heart", meter: "10 10 10 10", tune: "MORECAMBE", author: "Croly, George", composer: "Arkinson, Frederick C.", lyrics: "" },
  "310": { title: "Not All the Outward Forms on Earth", meter: "CMD", tune: "VOX DILECTI", author: "Watts, Isaac", composer: "Dykes, John B.", lyrics: "" },
  "311": { title: "Come, Holy Spirit, Heavenly Dove", meter: "CM", tune: "ST. AGNES", author: "Watts, Isaac", composer: "", lyrics: "" },
  "312": { title: "How Sweet and Awful Is the Place", meter: "CM", tune: "ST. COLUMBA", author: "Watts, Isaac", composer: "Irish melody; The English Hymnal, 1906", lyrics: "" },
  "313": { title: "Arise, My Soul, Arise", meter: "66 66 88 with repeat", tune: "LENOX", author: "Wesley, Charles", composer: "Edson, Lewis", lyrics: "" },
  "314": { title: "Amazing Grace! How Sweet the Sound", meter: "CM", tune: "NEW BRITAIN", author: "Newton, John", composer: "Virginia Harmony, 1831; Excell, Edwin O.", lyrics: "" },
  "315": { title: "Here Is Love", meter: "87 87 D", tune: "CYMRAEG", author: "Rees, William; Edwards, William; Williams, William", composer: "Lowry, Robert", lyrics: "" },
  "316": { title: "It Is Well with My Soul", meter: "", tune: "VILLE DU HAVRE", author: "Spafford, Horatio G.", composer: "Bliss, Philip P.", lyrics: "" },
  "317": { title: "Join All the Glorious Names", meter: "66 66 88", tune: "DARWALL", author: "Watts, Isaac", composer: "", lyrics: "" },
  "318": { title: "And Can It Be", meter: "88 88 88 with refrain", tune: "SAGINA", author: "Wesley, Charles", composer: "Campbell, Thomas", lyrics: "" },
  "319": { title: "One There Is, Above All Others", meter: "87 87 77", tune: "GODESBERG", author: "Newton, John", composer: "Albert, Heinrich", lyrics: "" },
  "320": { title: "Praise the Savior, Ye Who Know Him", meter: "888 5", tune: "ACCLAIM", author: "Kelly, Thomas", composer: "Traditional German melody", lyrics: "" },
  "321": { title: "O the Deep, Deep Love of Jesus", meter: "87 87 D", tune: "EBENEZER", author: "Francis, S. Trevor", composer: "Williams, Thomas J.", lyrics: "" },
   "322": { title: "I Sought the Lord", meter: "10 10 10 6", tune: "PEACE", author: "Jean Ingelow", composer: "Chadwick, George W.", lyrics: "" },
  "323": { title: "Praises for Thy Glorious Grace", meter: "87 87 with refrain", tune: "MT. CALVARY", author: "Minnick, Mark", composer: "Pinkston, Joan J.", lyrics: "" },
  "324": { title: "A Good High Priest Has Come", meter: "66 66 88", tune: "MILLENNIUM", author: "Cennick, John", composer: "English melody; Plymouth Collection of Hymns and Tunes, 1855", lyrics: "" },
  "325": { title: "Not What These Hands Have Done", meter: "SMD", tune: "TERRA BEATA", author: "Bonar, Horatius", composer: "Traditional English melody; adapt. Franklin L. Sheppard, 1915", lyrics: "" },
  "326": { title: "Jesus, My Highest Treasure", meter: "76 76 D", tune: "OSLO", author: "Liscovius, Salomon; Foster, Frederick William", composer: "Scandinavian folksong", lyrics: "" },
  "327": { title: "I Heard the Voice of Jesus Say (Kingsfold)", meter: "CMD", tune: "KINGSFOLD", author: "", composer: "", lyrics: "" },
  "328": { title: "I Heard the Voice of Jesus Say (Third Mode)", meter: "CMD", tune: "THIRD MODE MELODY", author: "Bonar, Horatius", composer: "Tallis, Thomas", lyrics: "" },
  "329": { title: "Before the Throne of God Above", meter: "", tune: "", author: "", composer: "", lyrics: "" },
  "330": { title: "Jesus, the Very Thought of Thee", meter: "CM", tune: "ST. AGNES", author: "Bernard of Clairvaux; Caswall, Edward", composer: "Dykes, John B.", lyrics: "" },
  "331": { title: "Ask Ye What Great Thing I Know", meter: "77 77 7", tune: "HENDON", author: "Schwedler, Johann C.; Kennedy, Benjamin Hall", composer: "Malan, Henri A. C.; Mason, Lowell", lyrics: "" },
  "332": { title: "Jesus, Thy Blood and Righteousness", meter: "LM", tune: "GERMANY", author: "von Zinzendorf, Nicolaus L.; Wesley, John", composer: "William Gardiner's Sacred Melodies, 1815", lyrics: "" },
  "333": { title: "I Will Sing of My Redeemer", meter: "87 87 D", tune: "HYFRYDOL", author: "Bliss, Philip P.", composer: "", lyrics: "" },
  "334": { title: "Jesus! What a Friend for Sinners", meter: "87 87 D", tune: "HYFRYDOL", author: "Chapman, J. Wilbur", composer: "Prichard, Rowland H.", lyrics: "" },
  "335": { title: "I Greet Thee, Who My Sure Redeemer Art", meter: "10 10 10 10", tune: "TOULON", author: "Attr. John Calvin in Strasbourgh Psalter, 1545; trans., Elizabeth L. Smith, 1868", composer: "Genevan Psalter, 1551", lyrics: "" },
  "336": { title: "My God, I Love Thee", meter: "CMD", tune: "KINGSFOLD", author: "Xavier, Francis; Caswall, Edward", composer: "English Country Songs, 1893; Vaughan Williams, Ralph", lyrics: "" },
  "337": { title: "There Is a Fountain Filled with Blood", meter: "CM with refrain", tune: "CLEANSING FOUNTAIN", author: "Cowper, William", composer: "American traditional; arr. Lowell Mason, 1830", lyrics: "" },
  "338": { title: "My Jesus, I Love Thee", meter: "11 11 11 11", tune: "GORDON", author: "Featherstone, William R.", composer: "Gordon, Adoniram J.", lyrics: "" },
  "339": { title: "My Hope Is Built on Nothing Less", meter: "88 88 88", tune: "THE SOLID ROCK", author: "Mote, Edward", composer: "William B. Bradbury, 1863", lyrics: "" },
  "340": { title: "How Deep the Father's Love for Us", meter: "", tune: "", author: "", composer: "", lyrics: "" },
  "341": { title: "In Christ Alone", meter: "", tune: "", author: "", composer: "", lyrics: "" },
  "342": { title: "I Hear the Words of Love", meter: "SM", tune: "ST. MICHAEL", author: "Bonar, Horatius", composer: "Bourgeois, Louis", lyrics: "" },
  "343": { title: "The Power of the Cross", meter: "", tune: "", author: "", composer: "", lyrics: "" },
  "344": { title: "Not All the Blood of Beasts", meter: "SM", tune: "SOUTHWELL", author: "Watts, Isaac", composer: "Daman, William; The Psalmes of David, 1579", lyrics: "" },
  "345": { title: "O for a Thousand Tongues to Sing", meter: "CM", tune: "AZMON", author: "Wesley, Charles", composer: "Gläser, Carl G.; Mason, Lowell", lyrics: "" },
  "346": { title: "Blessed Jesus, at Thy Word", meter: "78 78 88", tune: "LIEBSTER JESU", author: "Clausnitzer, Tobias; Geistreiches Gesang-Büchlein, 1707; Winkworth, Catherine", composer: "Ahle, Johann Rudolph; Bach, Johann Sebastian", lyrics: "" },
  "347": { title: "O Word of God Incarnate", meter: "76 76 D", tune: "MUNICH", author: "How, William Walsham", composer: "Neuvermehrtes Meiningisches Gesangbuch, 1693; Mendelssohn, Felix", lyrics: "" },
  "348": { title: "Thy Word Is Like a Garden, Lord", meter: "CMD", tune: "ELLACOMBE", author: "", composer: "", lyrics: "" },
  "349": { title: "How Firm a Foundation", meter: "11 11 11 11", tune: "FOUNDATION", author: "John Rippon's A Selection of Hymns, 1878", composer: "American folk tune; Funk's Genuine Church Music, 1832", lyrics: "" },
  "350": { title: "May the Mind of Christ My Savior", meter: "87 85", tune: "ST. LEONARDS", author: "Wilkinson, Kate B.", composer: "Barham-Gould, A. Cyril", lyrics: "" },
  "351": { title: "Take My Life, and Let It Be Consecrated", meter: "77 77 with repeat", tune: "HENDON", author: "Havergal, Frances R.", composer: "César, Malan Henri A.", lyrics: "" },
  "352": { title: "Be Thou My Vision", meter: "10 11 11 11", tune: "SLANE", author: "8th cent. hymn; Byrne, Mary Elizabeth; Hull, Eleanor", composer: "Irish folk melody", lyrics: "" },
  "353": { title: "Credo", meter: "CMD", tune: "OESTREICH", author: "Oestreich, David; \"The Apostles' Creed\"", composer: "Bauder, Josh", lyrics: "" },
  "354": { title: "The Apostles' Creed", meter: "", tune: "", author: "Ancient Creed", composer: "", lyrics: "" },
  "355": { title: "The Nicene Creed", meter: "", tune: "", author: "Ancient Creed", composer: "", lyrics: "" },
  "356": { title: "Come, Thou Fount", meter: "87 87 D", tune: "NETTLETON", author: "Robinson, Robert", composer: "John Wyeth's Repository of Sacred Music, 1813", lyrics: "" },
  "357": { title: "Christian Hearts in Love United", meter: "87 87 D", tune: "CASSEL", author: "von Zinzendorf, Nicolaus L.; Foster, Frederick W.", composer: "Moravian Chorale Book, 1735", lyrics: "" },
  "358": { title: "O for a Closer Walk with God", meter: "CM", tune: "CAITHNESS", author: "Cowper, William", composer: "Scottish Psalter, 1635; The English Hymnal, 1906", lyrics: "" },
  "359": { title: "Teach Me, My God and King", meter: "SM", tune: "FESTAL SONG", author: "Herbert, George; Weley, John", composer: "Walter, William H.", lyrics: "" },
  "360": { title: "My Soul, Be on Thy Guard", meter: "SM", tune: "BOYLSTON", author: "", composer: "", lyrics: "" },
  "361": { title: "Love Divine, All Loves Excelling", meter: "87 87 D", tune: "BEECHER", author: "Wesley, Charles", composer: "Zundel, John", lyrics: "" },
  "362": { title: "More Love to Thee", meter: "64 64 66 44", tune: "MORE LOVE TO THEE", author: "Prentiss, Elizabeth P.", composer: "Doane, William H.", lyrics: "" },
  "363": { title: "Jesus Call Us O'er the Tumult", meter: "87 87 D", tune: "PLEADING SAVIOR", author: "Alexander, Cecil F.", composer: "Leavitt's The Christian Lyre, 1830", lyrics: "" },
  "364": { title: "O Jesus, I Have Promised", meter: "76 76 D", tune: "ANGEL'S STORY", author: "Bode, John E.", composer: "Mann, Arthur", lyrics: "" },
  "365": { title: "O Church, Arise", meter: "", tune: "", author: "", composer: "", lyrics: "" },
  "366": { title: "Am I a Solider of the Cross?", meter: "CM", tune: "ARLINGTON", author: "Watts, Isaac", composer: "Arne, Thomas Augustine", lyrics: "" },
  "367": { title: "Soldiers of Christ, Arise", meter: "SMD", tune: "DIADEMATA", author: "Wesley, Charles", composer: "Elvey, George J.", lyrics: "" },
  "368": { title: "He Who Would Valiant Be", meter: "65 65 66 65", tune: "ST. DUNSTAN'S", author: "Bunyan, John; Dearmer, Percy", composer: "Douglas, Charles Winfred", lyrics: "" },
  "369": { title: "Guide Me, O Thou Great Jehovah", meter: "87 87 87 with repeat", tune: "CWM RHONDDA", author: "Williams, William; Williams, Peter", composer: "Hughes, John", lyrics: "" },
  "370": { title: "Jesus, Still Lead On", meter: "55 88 55", tune: "SEELENBRÄUTIGAM", author: "von Zinzendorf, Nicolaus L.; Borthwick, Jane", composer: "Drese, Adam", lyrics: "" },
  "371": { title: "My Faith Looks up to Thee", meter: "66 4 66 64", tune: "OLIVET", author: "Palmer, Ray", composer: "Mason, Lowell", lyrics: "" },
  "372": { title: "Savior, Like a Shepherd Lead Us", meter: "87 87 87", tune: "JESU, BONE PASTOR", author: "Thrupp, Dorothy A.", composer: "Wilcox, John Henry", lyrics: "" },
  "373": { title: "Approach, My Soul, the Mercy Seat", meter: "CM", tune: "BURFORD", author: "Newton, John", composer: "A. Williams's Supplement to Psalmody, 1780; Miller, Edward", lyrics: "" },
  "374": { title: "What Various Hindrances We Meet", meter: "LM", tune: "CONTRITION", author: "Cowper, William", composer: "von Rosenroth, Christian Knorr", lyrics: "" },
  "375": { title: "Lord, Teach Us How to Pray Aright", meter: "CM", tune: "ST. AGNES", author: "Montgomery, James", composer: "", lyrics: "" },
  "376": { title: "Come, My Soul, Thy Suit Prepare", meter: "77 77", tune: "VIENNA", author: "Newton, John", composer: "Knecht, Justin H.", lyrics: "" },
  "377": { title: "Amidst Us Our Beloved Stands", meter: "LM", tune: "ROCKINGHAM", author: "Spurgeon, Charles H.", composer: "A. Williams's Supplement to Psalmody, 1780; Miller, Edward", lyrics: "" },
  "378": { title: "To Avert from Men God's Wrath", meter: "77 77 77", tune: "REDHEAD", author: "Hus, John; Luther, Martin; La Trobe, Christian Ignatius", composer: "Redhead, Richard", lyrics: "" },
  "379": { title: "Thy Broken Body, Gracious Lord", meter: "LM", tune: "BOURBON", author: "Tregelles, Samuel P.", composer: "Hesperian Harp, 1848; McAllister, Louise", lyrics: "" },
  "380": { title: "Here, O My Lord, I See Thee Face to Face", meter: "10 10 10 10", tune: "MORECAMBE", author: "Horatius Bonar, 1855", composer: "Frederick C. Arkinson, 1870", lyrics: "" },
  "381": { title: "Father, We Thank Thee", meter: "98 98 D", tune: "RENDEZ À DIEU", author: "Greek, from the Didache, 110; Tucker, Bland", composer: "Bourgeois, Louis", lyrics: "" },
  "382": { title: "At the Lamb's High Feast We Sing", meter: "77 77 D", tune: "SALZBURG", author: "Latin 17th cent.; Campbell, Robert", composer: "Hintze, Jakob; Bach, Johann Sebastian", lyrics: "" },
  "383": { title: "Author of Life Divine", meter: "66 66 88 8", tune: "RHOSYMEDRE", author: "Wesley, Charles", composer: "Edwards, John David", lyrics: "" },
  "384": { title: "Jesus, Thou Joy of Loving Hearts", meter: "LM", tune: "QUEBEC", author: "Bernard of Clairvaux; Palmer, Ray", composer: "Baker, Henry W.", lyrics: "" },
  "385": { title: "The Church's One Foundation", meter: "76 76 D", tune: "AURELIA", author: "Stone, Samuel J.", composer: "Wesley, Samuel S.", lyrics: "" },
  "386": { title: "Christ Is Made the Sure Foundation", meter: "87 87 87", tune: "WESTMINSTER ABBEY", author: "Latin hymn 7th cent.; Neale, John Mason", composer: "Purcell, Henry; Hawkins, Ernest", lyrics: "" },
  "387": { title: "On Christ Salvation Rests Secure", meter: "LM", tune: "WINCHESTER NEW", author: "Medley, Samuel", composer: "Musikalisches Handbuch, 1690; Monk, William Henry", lyrics: "" },
  "388": { title: "For All the Saints", meter: "10 10 10 with alleluias", tune: "SINE NOMINE", author: "How, William Walsham", composer: "Vaughan Williams, Ralph", lyrics: "" },
  "389": { title: "O Give Us Homes", meter: "10 10 10 10 10 10", tune: "FINLANDIA", author: "", composer: "", lyrics: "" },
  "390": { title: "Built on the Rock the Church Doth Stand", meter: "88 88 88 8", tune: "KIRKEN DEN ER ET", author: "Grundtvig, Nikolai; Doving, Carl", composer: "Lindeman, Ludvig M.", lyrics: "" },
  "391": { title: "A Charge to Keep, I Have", meter: "SM", tune: "BOYLSTON", author: "Wesley, Charles", composer: "Mason, Lowell", lyrics: "" },
  "392": { title: "Hark, the Voice of Jesus Calling", meter: "87 87 D", tune: "ELLESDIE", author: "March, Daniel", composer: "Mozart, Wolfgang Amadeus; The Christian Lyre, 1833; Main, Hubert P.", lyrics: "" },
  "393": { title: "Christ for the World We Sing", meter: "66 4 66 64", tune: "ITALIAN HYMN", author: "Wolcott, Samuel", composer: "", lyrics: "" },
  "394": { title: "Come, Ye Thankful People, Come", meter: "77 77 D", tune: "ST. GEORGE'S WINDSOR", author: "Alford, Henry", composer: "Elvey, George J.", lyrics: "" },
  "395": { title: "Ye Servants of God, Your Master Proclaim", meter: "10 10 11 11", tune: "HANOVER", author: "Wesley, Charles", composer: "Croft, William", lyrics: "" },
  "396": { title: "Go, Labor On", meter: "LM", tune: "SONG 34", author: "Bonar, Horatius", composer: "Gibbons, Orlando", lyrics: "" },
  "397": { title: "A Mighty Fortress is Our God", meter: "87 87 66 66 7", tune: "EIN' FESTE BURG", author: "Luther, Martin; Hedge, Frederick H.", composer: "Luther, Martin; Bach, Johann Sebastian", lyrics: "" },
  "398": { title: "Thou Hidden Love of God", meter: "88 88 88", tune: "VATER UNSER", author: "Tersteegen, Gerhard; Wesley, John", composer: "Luther, Martin; Geistlich Lieder, 1539; Bach, Johann Sebastian", lyrics: "" },
  "399": { title: "Christ, Whose Glory Fills the Skies", meter: "77 77 77", tune: "DIX", author: "Wesley, Charles", composer: "", lyrics: "" },
  "400": { title: "Be Still, My Soul", meter: "10 10 10 10 10 10", tune: "FINLANDIA", author: "von Schlegel, Katrina A. D.; Borthwick, Jane", composer: "Sibelius, Jean; Jones, David Hugh", lyrics: "" },
  "401": { title: "Sometimes a Light Surprises", meter: "76 76 D", tune: "BLOMSTERTID", author: "Cowper, William", composer: "Swedish Koralbok, 1697", lyrics: "" },
  "402": { title: "Children of the Heavenly Father", meter: "LM", tune: "TRYGGARE KAN INGEN VARA", author: "Sandell-Berg, Caroline; Olsen, Ernst", composer: "Swedish folk song", lyrics: "" },
  "403": { title: "Rejoice, Believer, in the Lord", meter: "CM", tune: "BRADFIELD", author: "Newton, John", composer: "Calkin, J. B.", lyrics: "" },
  "404": { title: "How Sweet the Name of Jesus Sounds", meter: "CM", tune: "ST. PETER", author: "Newton, John", composer: "Reinagle, Alexander Robert", lyrics: "" },
  "405": { title: "Like a River Glorious", meter: "11 11 11 11 with refrain", tune: "WYE VALLEY", author: "Havergal, Frances R.", composer: "Mountain, James", lyrics: "" },
  "406": { title: "Give to the Wind Thy Fears", meter: "SM", tune: "FESTAL SONG", author: "Gerhardt, Paul; Wesley, John", composer: "William Henry Walter, 1894", lyrics: "" },
  "407": { title: "Not What I Am, O Lord", meter: "10 10 10 10", tune: "LANGRAN", author: "Bonar, Horatius", composer: "Langran, James", lyrics: "" },
  "408": { title: "Jesus, Lover of My Soul", meter: "77 77 D", tune: "ABERYSTWYTH", author: "Wesley, Charles", composer: "Parry, Joseph", lyrics: "" },
  "409": { title: "Thou Sweet Beloved Will of God", meter: "LM", tune: "GERMANY", author: "Tersteegen, Gerhard; Bevan, Frances", composer: "William Gardiner's Sacred Melodies, 1815", lyrics: "" },
  "410": { title: "If Thou But Trust in God to Guide Thee", meter: "98 98 88", tune: "NEUMARK", author: "Neumark, Georg; Winkworth, Catherine", composer: "Neumark, Georg", lyrics: "" },
  "411": { title: "What God Ordains Is Always Good", meter: "87 87 44 77", tune: "WAS GOTT TUT", author: "Rodigast, Samuel; The Lutheran Hymnal, 1941", composer: "Gastorius, Servus", lyrics: "" },
  "412": { title: "God Moves in a Mysterious Way", meter: "CM", tune: "DUNDEE", author: "Cowper, William", composer: "Scottish Psalter, 1615", lyrics: "" },
  "413": { title: "Sun of My Soul", meter: "LM", tune: "HURSLEY", author: "Keble, John", composer: "Katholisches Gesangbuch, Vienna, 1774", lyrics: "" },
  "414": { title: "O Thou in Whose Presence", meter: "11 8 11 8", tune: "DAVIS", author: "Swain, Joseph", composer: "Lewis, Freeman", lyrics: "" },
  "415": { title: "Abide with Me", meter: "10 10 10 10", tune: "EVENTIDE", author: "Lyte, Henry Francis", composer: "Monk, William Henry", lyrics: "" },
  "416": { title: "Glorious Things of Thee Are Spoken", meter: "87 87 D", tune: "AUSTRIAN HYMN", author: "Newton, John", composer: "Haydn, Franz J.", lyrics: "" },
  "417": { title: "Jesus, Priceless Treasure", meter: "66 5 66 5 78 6", tune: "JESU, MEINE FREUDE", author: "Franck, Johann; Winkworth, Catherine", composer: "Crüger, Johann; Bach, Johann Sebastian", lyrics: "" },
  "418": { title: "We Walk by Faith and Not by Sight", meter: "CM", tune: "ST. BOTOLPH", author: "Alford, Henry", composer: "Slater, Gordon", lyrics: "" },
  "419": { title: "Jerusalem the Golden", meter: "76 76 D", tune: "EWING", author: "Bernard of Cluny; Neale, John Mason", composer: "Ewing, Alexander C.", lyrics: "" },
  "420": { title: "Jerusalem, My Happy Home", meter: "CM", tune: "LAND OF REST", author: "F. B. P. 16th cent.; Augustine", composer: "Traditional American melody; Muchanan, Annabel M.", lyrics: "" },
  "421": { title: "The Sands of Time Are Sinking", meter: "76 76 76 75", tune: "RUTHERFORD", author: "Cousin, Anne R.; Rutherford, Samuel", composer: "Urhan, Chretien", lyrics: "" },
  "422": { title: "Oh, What Their Joy and Their Glory Must Be", meter: "10 10 10 10", tune: "O QUANTA QUALIA", author: "Abelard, Peter; Neale, John Mason", composer: "Paris Antiphoner, 1681", lyrics: "" },
  "423": { title: "God, That Madest Earth and Heavens", meter: "84 84 888 4", tune: "AR HYD Y NOS", author: "st. 1, Reginald Heber, 1827; st. 2, William Mercer, 1864; st. 3, Richard Whately, 1855", composer: "Welsh traditional melody; harm. Ralph Vaughan Williams, 1906", lyrics: "" },
  "424": { title: "In God, My Faithful God", meter: "66 77 77", tune: "AUF MEINEN LIEBEN GOTT", author: "Sigismund Weingartner, 1607; tr. Catherine Winkworth, 1863", composer: "Deutsche Lieder, 1574", lyrics: "" },
  "425": { title: "Dear Refuge of My Weary Soul", meter: "", tune: "", author: "Anne Steele", composer: "Matt Merker", lyrics: "" },
  "426": { title: "Thou Hidden Source of Calm Repose", meter: "88 88 88", tune: "STELLA", author: "Charles Wesley, 1749", composer: "Arr. in Easy Hymn Tunes, 1851", lyrics: "" },
  "427": { title: "I Asked the Lord That I Might Grow", meter: "LM", tune: "O WALY WALY", author: "John Newton, 1791", composer: "Traditional English melody", lyrics: "" },
  "428": { title: "Nearer, Still Nearer", meter: "9 10 9 10 with repeat", tune: "MORRIS", author: "Leila N. Morris, 1862–1929", composer: "Leila N. Morris, 1862–1929", lyrics: "" },
  "429": { title: "The Son of God Goes Forth to War", meter: "CMD", tune: "GREYOAKS", author: "Reginald Heber, 1827", composer: "Gregory D. Wilbur, 1994", lyrics: "" },
  "430": { title: "O Gladsome Light", meter: "66 76 67", tune: "NUNC DIMITTIS", author: "Greek Phos Hilaron, c. 200; Bridges, Robert S.", composer: "Bourgeois, Louis; Goudimel, Claude", lyrics: "" },
  "431": { title: "The Duteous Day Now Closeth", meter: "77 67 78", tune: "INNSBRUCK", author: "Gerhardt, Paul; Bridges, Robert S.", composer: "Isaak, Heinrich; Bach, Johann Sebastian", lyrics: "" },
  "432": { title: "May the Grace of Christ Our Savior", meter: "87 87 D", tune: "BEACH SPRING", author: "Newton, John", composer: "Traditional American melody; The Sacred Harp,1844", lyrics: "" },
  "107A": { title: "Give Thanks to GOD, He Reigns Above", meter: "LM", tune: "PUER NOBIS", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "107B": { title: "Praise the LORD, for He is Good", meter: "77 77 77", tune: "DIX", author: "", composer: "", lyrics: "" },
  "119A": { title: "How Blessed the Perfect in the Way", meter: "LM", tune: "ROCKINGHAM", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119B": { title: "How Shall the Young Direct Their Way?", meter: "LM", tune: "MARYTON", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119C": { title: "Thy Servant, Blessed by Thee, Shall Live", meter: "CM", tune: "ARLINGTON", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119D": { title: "My Grieving Soul Revive, O Lord", meter: "CM", tune: "MARTYRDOM", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119E": { title: "Teach Me, O LORD, Thy Way of Truth", meter: "LM", tune: "OLIVE'S BROW", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119F": { title: "Thy Promised Mercies Send to Me", meter: "CM", tune: "ST. AGNES", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119G": { title: "LORD, Thy Word to Me Remember", meter: "87 87", tune: "EBENEZER", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119H": { title: "Thou Art My Portion, LORD", meter: "SM", tune: "BOYLSTON", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119I": { title: "According to Your Word, O LORD", meter: "CM", tune: "WINCHESTER OLD", author: "Book of Psalms for Worship", composer: "", lyrics: "" },
  "119J": { title: "Thou, Who Didst Make and Fashion Me", meter: "LM", tune: "BLOCKLEY", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119K": { title: "My Soul for Thy Salvation Faints", meter: "CM", tune: "ESSLINGEN", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119L": { title: "Forever Settled in the Heavens", meter: "LM", tune: "BOURBON", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119M": { title: "How I Love Thy Law, O Lord", meter: "77 77", tune: "CANTERBURY", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119N": { title: "Thy Word Sheds Light upon My Path", meter: "LM", tune: "DISTRESS", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119O": { title: "Deceit and Falsehood I Abhor", meter: "88 88 88", tune: "VATER UNSER", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119P": { title: "I Have Followed Truth and Justice", meter: "87 87 D", tune: "RESTORATION", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119Q": { title: "Thy Wondrous Testimonies, Lord", meter: "LM", tune: "QUEBEC", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119R": { title: "O LORD, Thy Perfect Righteousness", meter: "CM", tune: "BURFORD", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119S": { title: "O LORD, My Earnest Cry", meter: "SM", tune: "SOUTHWELL", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119T": { title: "Regard My Grief and Rescue Me", meter: "LM", tune: "KEDRON", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119U": { title: "Though Mighty Foes Assail Me, Lord", meter: "CM", tune: "MORNING SONG", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "119V": { title: "O Let My Supplicating Cry", meter: "LM", tune: "DISTRESS", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "136": { title: "Let Us, with a Gladsome Mind", meter: "", tune: "MONKLAND", author: "", composer: "", lyrics: "" },
  "147A": { title: "With Songs and Honors Sounding Loud", meter: "", tune: "", author: "", composer: "", lyrics: "" },
  "147B": { title: "Oh, Sing Ye Hallelujah!", meter: "76 76 D", tune: "PSALM 147", author: "Gregory D. Wilbur, 2007", composer: "", lyrics: "" },
  "148A": { title: "From Heav'n O Praise the LORD", meter: "", tune: "", author: "", composer: "", lyrics: "" },
  "148B": { title: "Praise the LORD! Praise from the Heavens", meter: "87 87 D", tune: "ODE TO JOY", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "19A": { title: "The Heavens Declare Thy Glory, LORD", meter: "LM", tune: "UXBRIDGE", author: "", composer: "", lyrics: "" },
  "19B": { title: "The Heavens Are Telling the Glory of God", meter: "12 11 12 11", tune: "KREMSER", author: "Julie and Timothy Tennent", composer: "Nederlandtsch Gedenckclank, 1626; arr. Edward Kremser, 1877", lyrics: "" },
  "23A": { title: "My Shepherd Will Supply My Need", meter: "CMD", tune: "RESIGNATION", author: "Isaac Watts, 1719", composer: "Southern Harmony, 1835", lyrics: "" },
  "23B": { title: "The King of Love My Shepherd Is", meter: "87 87", tune: "ST. COLUMBA", author: "Henry W. Baker, 1868", composer: "", lyrics: "" },
  "23D": { title: "The LORD's My Shepherd", meter: "CM", tune: "CRIMOND", author: "Scottish Psalter, 1650", composer: "Jessie Seymour Irvine, 1871; harm. David Grant, 1872", lyrics: "" },
  "35A": { title: "Contend, O Lord, with Those Who Do Contend", meter: "SMD", tune: "TERRA BEATA", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "35B": { title: "Your Mercy and Your Truth, O LORD", meter: "CM", tune: "WINCHESTER OLD", author: "", composer: "", lyrics: "" },
  "39A": { title: "Thus I Resolved Before the LORD", meter: "CM", tune: "SALISBURY", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "39B": { title: "Behold, O LORD, My Days Are Made", meter: "CM", tune: "ARLINGTON", author: "Charles H. Spurgeon, 1866", composer: "", lyrics: "" },
  "42A": { title: "As Longs the Deer", meter: "CM", tune: "BELMONT", author: "", composer: "", lyrics: "" },
  "42B": { title: "As the Deer Pants for Water Clear", meter: "CM", tune: "ST. COLUMBA", author: "Julie and Timothy Tennent", composer: "", lyrics: "" },
  "46A": { title: "God Is Our Refuge and Our Strength", meter: "88 88 66 66 8", tune: "EIN' FESTE BURG", author: "The Book of Psalms for Worship", composer: "", lyrics: "" },
  "46B": { title: "God Is the Refuge of His Saints", meter: "LM", tune: "TRURO", author: "", composer: "", lyrics: "" },
  "50A": { title: "The Mighty God, the Lord", meter: "SMD", tune: "DIADEMATA", author: "Scottish Psalter 1650", composer: "", lyrics: "" },
  "50B": { title: "Hear, O My People, I Will Speak", meter: "88 88 88", tune: "MELITA", author: "", composer: "", lyrics: "" },
  "63A": { title: "O Lord, My God, Most Earnestly", meter: "CMD", tune: "RESIGNATION", author: "The Psalter, 1912", composer: "", lyrics: "" },
  "63B": { title: "O God, You Are My God Alone", meter: "LM", tune: "PUER NOBIS", author: "", composer: "", lyrics: "" },
  "66A": { title: "Come, All Ye People, Bless Our God", meter: "88 6 88 6", tune: "ADOWA", author: "", composer: "", lyrics: "" },
  "66B": { title: "O All You Peoples, Bless Our God", meter: "CMD", tune: "FOREST GREEN", author: "Book of Psalms for Worship", composer: "", lyrics: "" },
  "67A": { title: "O God, to Show Us Mercy", meter: "76 76 D", tune: "MEIRIONYDD", author: "", composer: "", lyrics: "" },
  "67B": { title: "O God, Show Mercy to Us", meter: "13 13 13 13 13 13", tune: "THAXTED", author: "Book of Psalms for Worship", composer: "", lyrics: "" },
  "68A": { title: "O Lord, Thou Hast Ascended", meter: "", tune: "", author: "", composer: "", lyrics: "" },
  "68B": { title: "Let God Arise in All His Might", meter: "LM", tune: "BOURBON", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "69A": { title: "Thy Lovingkindness, Lord", meter: "10 10 10 10", tune: "EVENTIDE", author: "", composer: "", lyrics: "" },
  "69B": { title: "Save Me, O God", meter: "CMD", tune: "KINGSFOLD", author: "Isaac Watts, 1719", composer: "", lyrics: "" },
  "70A": { title: "In Haste, O God, Attend My Call", meter: "", tune: "", author: "", composer: "", lyrics: "" },
  "70B": { title: "Make Haste, O God, My Soul to Bless!", meter: "LM", tune: "KEDRON", author: "Charles H. Spurgeon, 1866", composer: "", lyrics: "" },
  "86A": { title: "Bow Down Thy Ear, O LORD", meter: "LM", tune: "MARYTON", author: "", composer: "", lyrics: "" },
  "86B": { title: "Hear Me, O LORD, and Answer Me", meter: "LM", tune: "BLOCKLEY", author: "Trinity Psalter Hymnal", composer: "", lyrics: "" },
  "8A": { title: "O LORD, Our Lord, in All the Earth", meter: "CM", tune: "CLINTON", author: "The Psalter, 1912", composer: "Joseph P. Holbrook, 1870", lyrics: "" },
  "8B": { title: "O LORD, Our Lord, How Wondrous Great", meter: "CM", tune: "DUNLAP'S CREEK", author: "Isaac Watts, 1719", composer: "Samuel McFarland, c. 1816", lyrics: "" }
};